packages:
  - packages/*
  - apps/*
minimumReleaseAgeExclude:
  - playwright-core@1.64.0
  - playwright@1.64.0
allowBuilds:
  onnxruntime-node: false
  protobufjs: false
virtualStoreDir: node_modules/.pnpm
