export default async (page) => {
  page.on('console', m => { if (m.type() === 'error') console.log('console error:', m.text().slice(0, 200)); });
  await page.waitForTimeout(2500);
  if (await page.locator('.help').count()) await page.keyboard.press('Escape');
  await page.getByRole('button', { name: /Free shift/ }).click();
  await page.waitForTimeout(300);
  await page.getByRole('button', { name: 'Ground + Tower', exact: true }).click();
  await page.getByRole('button', { name: 'Start shift' }).click();
  await page.waitForTimeout(5000);
  console.log('hook:', await page.evaluate(() => typeof window.squawkDebug));
  await page.keyboard.press('3');
  await page.waitForTimeout(8000);
  await page.evaluate(() => window.squawkDebug?.('crash'));
  await page.waitForTimeout(1500);
  console.log('strips:', (await page.locator('.strip').allTextContents()).map(t => t.replace(/\s+/g, ' ').slice(0, 40)).join(' | '));
  console.log('state:', await page.evaluate(() => { const s = window.squawkSnap(); return JSON.stringify({ tick: s.tick, inc: s.incidents, ac: s.aircraft.map(a => a.cs + ':' + a.phase).join(','), radio: s.radio.length, coverage: s.coverage }).slice(0, 900); }));
  console.log('log:', (await page.locator('.comms .ln').allTextContents()).slice(-4).join(' | '));
  await page.screenshot({ path: 'C:/Users/alexr/AppData/Local/Temp/claude/K--Repositories-Squawk/fe16d656-cda8-423a-97e0-ec0123a19f0c/scratchpad/play/crashdbg.png' });
  console.log('alerts:', (await page.locator('.alert').allTextContents()).map(t => t.replace(/\s+/g, ' ')).join(' | '));
};
