import { readFileSync } from 'node:fs';
import { buildWorld, createShift, DIFFICULTY, step, find, runwayAt, depGap, geo } from '../packages/sim/src/index.ts';
const pack = JSON.parse(readFileSync(new URL('../data/airports/EGLL/airport.json', import.meta.url), 'utf8'));
const day = JSON.parse(readFileSync(new URL('../data/days/EGLL-2026-08-28.json', import.meta.url), 'utf8'));
const world = buildWorld([pack]); const apt = world.primary;
const cfg = { seed: 7, airports: ['EGLL'], days: [day], start: Date.parse('2026-08-28T' + (process.env.H ?? '07') + ':00:00Z') / 1000, durationS: 3600, traffic: 1, coverage: [], difficulty: DIFFICULTY.standard, mode: 'free' as const };
const st = createShift(world, cfg);
while (st.tick < +process.argv[2]) step(world, cfg, st);
const ac = find(st, process.argv[3])!;
const end = apt.ends[ac.runway!];
console.log(ac.cs, ac.phase, 'gap', depGap(world, st, ac), 'lastDep', JSON.stringify(st.apts[0].lastDep));
for (const o of st.aircraft) if (o !== ac && ((o.runway && apt.ends[o.runway]?.runway === end.runway && ['takeoff','landing','lineup','lined'].includes(o.phase)) || (o.onGround && runwayAt(apt, o) === end.runway))) console.log(' on rwy:', o.cs, o.phase, Math.round(o.x), Math.round(o.y));
for (const o of st.aircraft) if (o.kind === 'arr' && o.runway && apt.ends[o.runway]?.runway === end.runway && o.nav.established) console.log(' arr est:', o.cs, (geo.dist(o, apt.ends[o.runway].thr) / 1852).toFixed(1));
console.log('arr', st.apts[0].arr, 'dep', st.apts[0].dep);
